# a mybinder.org-ready environment for demoing jb_toc
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jb-toc-demo
#
name: jb-toc-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.10,<3.13
  - jupyterlab >=4.0.0,<5
  # labextension build dependencies
  - nodejs >=20
  - pip
  - wheel
  # additional packages for demos
  # - ipywidgets
