name: "Step 1: Prep Release"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g., v0.0.0)"
        required: true
      branch:
        description: "The branch to target"
        required: false
      since:
        description: "Use PRs with activity since this date or git reference"
        required: false
      since_last_stable:
        description: "Use PRs with activity since the last stable git tag"
        required: false
        type: boolean

jobs:
  prep_release:
    runs-on: ubuntu-latest
    environment: publishing
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Prep Release
        id: prep-release
        uses: jupyter-server/jupyter_releaser/.github/actions/prep-release@v2
        with:
          token: ${{ secrets.PUBLISH_GITHUB_PAT }}
          branch: ${{ github.event.inputs.branch }}
          since: ${{ github.event.inputs.since }}
          since_last_stable: ${{ github.event.inputs.since_last_stable }}

      - name: Force-create/move tag on remote
        env:
          TAG: ${{ github.event.inputs.tag }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin "${BRANCH}" --depth=1
          git checkout -B "${BRANCH}" "origin/${BRANCH}"
          git tag -f "${TAG}"
          git push origin "refs/tags/${TAG}" --force

      - name: "** Next Step **"
        run: |
          echo "Tag pushed: ${{ github.event.inputs.tag }}"
          echo "Optional): Review Draft Release: ${{ steps.prep-release.outputs.release_url }}"
