name: "Step 2: Publish Release"
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The target branch"
        required: false
        default: "main"
      release_url:
        description: "The URL of the draft GitHub release"
        required: false
      tag:
        description: "Release tag (e.g., v0.0.0)"
        required: true

jobs:
  publish_release:
    runs-on: ubuntu-latest
    environment: publishing
    permissions:
      # This is useful if you want to use PyPI trusted publisher
      # and NPM provenance
      id-token: write
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
        
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Release tag
        env:
          TAG: ${{ github.event.inputs.tag }}
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin "${BRANCH}" --depth=1
          git checkout -B "${BRANCH}" "origin/${BRANCH}"
          git tag -f "${TAG}"
          git push origin "refs/tags/${TAG}" --force

      - name: Populate Release
        id: populate-release
        uses: jupyter-server/jupyter_releaser/.github/actions/populate-release@v2
        with:
          token: ${{ secrets.PUBLISH_GITHUB_PAT }}
          branch: ${{ github.event.inputs.branch }}
          release_url: ${{ github.event.inputs.release_url }}
          steps_to_skip: check-python,tag-release

      - name: Finalize Release
        id: finalize-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: jupyter-server/jupyter_releaser/.github/actions/finalize-release@v2
        with:
          token: ${{ secrets.PUBLISH_GITHUB_PAT }}
          release_url: ${{ steps.populate-release.outputs.release_url }}

      - name: "** Next Step **"
        if: ${{ success() }}
        run: |
          echo "Verify the final release"
          echo ${{ steps.finalize-release.outputs.release_url }}

      - name: "** Failure Message **"
        if: ${{ failure() }}
        run: |
          echo "Failed to Publish the Draft Release Url:"
          echo ${{ steps.populate-release.outputs.release_url }}
          